In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso, Ridge, LinearRegression, SGDRegressor
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split, RandomizedSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from scipy.stats import uniform

In [2]:
df = pd.read_csv("files/data-7.csv")
df

x         y
0   5.31996  2.214690
1   3.71996  0.783416
2   7.91996  1.523031
3   0.81996 -2.002046
4   7.71996  1.426515
..      ...       ...
95  3.01996  0.441281
96  0.11996 -3.653027
97  0.51996 -2.009519
98  0.31996 -2.199633
99  6.61996  1.923364

[100 rows x 2 columns]

In [3]:
x, y = df["x"].values.reshape(-1, 1), df["y"].values.reshape(-1, 1)

In [4]:
x

array([[ 5.31995956],
       [ 3.71995956],
       [ 7.91995956],
       [ 0.81995956],
       [ 7.71995956],
       [ 5.91995956],
       [ 9.31995956],
       [ 9.11995956],
       [-0.18004044],
       [ 4.31995956],
       [ 1.71995956],
       [ 7.61995956],
       [ 1.31995956],
       [ 8.31995956],
       [-0.08004044],
       [ 5.51995956],
       [ 8.71995956],
       [ 2.61995956],
       [ 4.41995956],
       [ 2.21995956],
       [ 2.01995956],
       [-0.28004044],
       [ 1.21995956],
       [ 5.21995956],
       [ 6.41995956],
       [ 8.01995956],
       [ 6.91995956],
       [ 9.51995956],
       [ 9.41995956],
       [ 0.41995956],
       [ 4.21995956],
       [ 1.61995956],
       [ 9.21995956],
       [ 3.21995956],
       [ 3.51995956],
       [ 8.11995956],
       [ 0.01995956],
       [ 3.11995956],
       [ 7.31995956],
       [ 7.11995956],
       [ 1.91995956],
       [ 5.11995956],
       [ 4.51995956],
       [ 2.91995956],
       [ 5.01995956],
       [ 8

In [5]:
y

array([[ 2.21468984],
       [ 0.78341598],
       [ 1.52303091],
       [-2.00204576],
       [ 1.42651523],
       [ 1.23755158],
       [ 2.97144113],
       [ 3.25327443],
       [-4.32086913],
       [ 1.36469963],
       [-0.46524421],
       [ 1.88681274],
       [-0.07231573],
       [ 1.41162992],
       [-3.7340467 ],
       [ 1.82845309],
       [ 1.51964816],
       [ 1.18722776],
       [ 2.17112399],
       [ 0.13584433],
       [ 0.47827133],
       [-5.18296261],
       [-1.40221504],
       [ 1.61762387],
       [ 1.42566729],
       [ 2.06128261],
       [ 1.46581406],
       [ 3.19324745],
       [ 2.30025147],
       [-3.2829932 ],
       [ 1.83210999],
       [-0.0982722 ],
       [ 2.11953062],
       [ 0.67130426],
       [ 0.64182918],
       [ 2.14657524],
       [-3.94270173],
       [ 0.5016538 ],
       [ 2.35159554],
       [ 1.37837883],
       [-0.27795887],
       [ 1.73084407],
       [ 0.92984529],
       [ 0.9853365 ],
       [ 1.90446205],
       [ 2

In [6]:
poly = PolynomialFeatures(degree=4)

x_poly = poly.fit_transform(x)

x_train_poly, x_test_poly, y_train_poly, y_test_poly = train_test_split(
    x_poly,
    y,
    test_size=.2,
    random_state=42
)

In [7]:
LinearRegression_model = LinearRegression().fit(x_train_poly, y_train_poly)

In [8]:
r2_score(y_test_poly, LinearRegression_model.predict(x_test_poly))

0.9260744757841065

In [9]:
poly_pipeline = PolynomialFeatures(degree=4)
LinearRegression_pipeline = LinearRegression()

Pipeline_model = make_pipeline(
    poly_pipeline,
    LinearRegression_pipeline
)

result = cross_val_score(Pipeline_model,
    x,
    y,
    cv=5,
    scoring="neg_mean_absolute_error"
)

result

array([-0.42302857, -0.43878222, -0.29099818, -0.35727151, -0.35023829])

In [10]:
result.mean()

np.float64(-0.37206375402046243)

In [11]:
mask = {"alpha": [0.001, 0.01, 0.05, 1, 2, 3, 7, 15, 30]}

In [12]:
Lasso_model = Lasso()

mask_model = GridSearchCV(
    Lasso_model,
    mask,
    scoring="r2",
    cv=5
).fit(x_poly, y)

mask_model.best_params_

c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.769e+00, tolerance: 2.447e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.442e+00, tolerance: 2.217e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the sca

{'alpha': 0.001}

In [13]:
mask = {"lasso__alpha": [0.001, 0.01, 0.05, 1, 2, 3, 7, 15, 30]}

In [14]:
Pipeline_mask_model = make_pipeline(
    poly,
    Lasso_model,
)

result = GridSearchCV(Pipeline_mask_model, mask, scoring="r2", cv=5).fit(x_poly, y)
result.best_params_

c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.620e+00, tolerance: 2.447e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.309e+00, tolerance: 2.217e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the sca

{'lasso__alpha': 0.001}

## ЗАДАНИЕ 1

In [15]:
mask = {"ridge__alpha": [0.001, 0.01, 0.05, 1, 2, 3, 7, 15, 30]}

In [16]:
Ridge_model = Ridge()
poly = PolynomialFeatures()

Pipeline_mask_model = make_pipeline(
    poly,
    Ridge_model,
)

result = cross_val_score(
    Pipeline_mask_model,
    x,
    y,
    cv=5,
    scoring="neg_mean_absolute_error"
)

print(result)

result = GridSearchCV(Pipeline_mask_model, mask, scoring="neg_mean_squared_error", cv=5).fit(x_poly, y)
print(result.best_params_)

c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 4.251676043433753e-20.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 5.149027032809075e-20.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 3.513817076504009e-20.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 4.09558932129079

[-0.65497726 -0.61058791 -0.47544097 -0.51335442 -0.61893131]
{'ridge__alpha': 0.01}


c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.8619165304945084e-16.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.2736165364049456e-16.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.4849451699806412e-16.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_ridge.py:228: LinAlgWarning: An ill-conditioned matrix detected: slice 0 has rcond = 1.50766750985

In [17]:
mask = {"lasso__alpha": [0.001, 0.01, 0.05, 1, 2, 3, 7, 15, 30]}

In [18]:
scale_model = StandardScaler()
Lasso_model = Lasso()

Pipeline_mask_model = make_pipeline(
    scale_model,
    Lasso_model,
)

result = cross_val_score(
    Pipeline_mask_model,
    x,
    y,
    cv=7,
    scoring="r2"
)

print(result)

result = GridSearchCV(Pipeline_mask_model, mask, scoring="r2", cv=7).fit(x_poly, y)
print(result.best_params_)

c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.211e-01, tolerance: 2.485e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.069e-01, tolerance: 2.887e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the sca

[0.30699339 0.3025161  0.39315485 0.3633523  0.37622907 0.35897719
 0.26314064]
{'lasso__alpha': 0.001}


c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.633e-01, tolerance: 3.216e-02
  model = cd_fast.enet_coordinate_descent(


## ЗАДАНИЕ 2

In [19]:
df = pd.read_csv("files/data-3.csv")
df

x1        x2         y
0   9.057719  3.032976 -0.220864
1   6.757719  8.732976  0.179764
2   2.757719  4.932976  0.758206
3   7.757719  1.332976  4.051974
4   9.957719  0.332976  3.547998
..       ...       ...       ...
95  3.057719  5.132976  0.841007
96  3.457719  7.732976  0.369499
97  9.457719  3.832976 -2.004597
98  4.157719  0.232976  7.847620
99  2.957719  7.032976  0.132068

[100 rows x 3 columns]

In [20]:
x, y = df[["x1", "x2"]].values, df["y"].values

In [21]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=.2,
    random_state=42
)

In [22]:
mask = {"ridge__alpha": [0.001, 0.01, 0.05, 1, 2, 3, 7, 15, 30]}

In [23]:
poly_model = PolynomialFeatures()
ridge_model = Ridge()

Pipeline_mask_model = make_pipeline(
    poly_model,
    ridge_model,
)

result = GridSearchCV(
    Pipeline_mask_model,
    mask,
    scoring="neg_mean_squared_error",
    cv=5
).fit(x_train, y_train)

result.best_params_

{'ridge__alpha': 0.05}

In [24]:
mask = {"sgdregressor__alpha": [0.001, 0.01, 0.05, 1, 2, 3, 7, 15, 30]}

In [25]:
poly_model = PolynomialFeatures()
scale_model = StandardScaler()

results = dict()
for penalty in ["l2", "l1", "elasticnet", None]:
    for loss in ["squared_error", "huber", "epsilon_insensitive", "squared_epsilon_insensitive"]:
        SGDRegressor_model = SGDRegressor(
            loss=loss,
            penalty=penalty
        )

        Pipeline_mask_model = make_pipeline(
            poly_model,
            scale_model,
            SGDRegressor_model,
        )

        result = GridSearchCV(
            Pipeline_mask_model,
            mask,
            scoring="neg_mean_squared_error",
            cv=6
        ).fit(x_train, y_train)

        results[f"{penalty}|{loss}"] = result.best_params_

In [26]:
results

{'l2|squared_error': {'sgdregressor__alpha': 0.001},
 'l2|huber': {'sgdregressor__alpha': 0.001},
 'l2|epsilon_insensitive': {'sgdregressor__alpha': 0.001},
 'l2|squared_epsilon_insensitive': {'sgdregressor__alpha': 0.001},
 'l1|squared_error': {'sgdregressor__alpha': 0.001},
 'l1|huber': {'sgdregressor__alpha': 0.001},
 'l1|epsilon_insensitive': {'sgdregressor__alpha': 0.001},
 'l1|squared_epsilon_insensitive': {'sgdregressor__alpha': 0.001},
 'elasticnet|squared_error': {'sgdregressor__alpha': 0.001},
 'elasticnet|huber': {'sgdregressor__alpha': 0.001},
 'elasticnet|epsilon_insensitive': {'sgdregressor__alpha': 0.001},
 'elasticnet|squared_epsilon_insensitive': {'sgdregressor__alpha': 0.001},
 'None|squared_error': {'sgdregressor__alpha': 3},
 'None|huber': {'sgdregressor__alpha': 15},
 'None|epsilon_insensitive': {'sgdregressor__alpha': 0.001},
 'None|squared_epsilon_insensitive': {'sgdregressor__alpha': 0.01}}

In [27]:
mask = {"ridge__alpha": [0.001, 0.01, 0.05, 1, 2, 3, 7, 15, 30]}

In [28]:
poly_model = PolynomialFeatures()

results = dict()
for solver in ["auto", "svd", "cholesky", "lsqr", "sparse_cg", "sag", "saga", "lbfgs"]:
    Ridge_model = Ridge(
        solver=solver,
        positive=True if solver in ["auto", "lbfgs"] else False
    )

    Pipeline_mask_model = make_pipeline(
        poly_model,
        Ridge_model,
    )

    result = GridSearchCV(
        Pipeline_mask_model,
        mask,
        scoring="neg_mean_squared_error",
        cv=6
    ).fit(x_train, y_train)

    results[f"{solver}"] = result.best_params_

c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the 

In [29]:
results

{'auto': {'ridge__alpha': 0.001},
 'svd': {'ridge__alpha': 0.05},
 'cholesky': {'ridge__alpha': 0.05},
 'lsqr': {'ridge__alpha': 0.05},
 'sparse_cg': {'ridge__alpha': 0.05},
 'sag': {'ridge__alpha': 0.001},
 'saga': {'ridge__alpha': 0.001},
 'lbfgs': {'ridge__alpha': 0.001}}

In [30]:
mask = {"ridge__alpha": uniform(loc=0, scale=4)}

In [31]:
poly_model = PolynomialFeatures()

results = dict()
for solver in ["auto", "svd", "cholesky", "lsqr", "sparse_cg", "sag", "saga", "lbfgs"]:
    Ridge_model = Ridge(
        solver=solver,
        positive=True if solver in ["auto", "lbfgs"] else False
    )

    Pipeline_mask_model = make_pipeline(
        poly_model,
        Ridge_model,
    )

    result = RandomizedSearchCV(
        Pipeline_mask_model,
        mask,
        scoring="neg_mean_squared_error",
        cv=6
    ).fit(x_train, y_train)

    results[f"{solver}"] = result.best_params_

c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\ebeck\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the 

In [32]:
results

{'auto': {'ridge__alpha': np.float64(1.8651957851012284)},
 'svd': {'ridge__alpha': np.float64(0.4506328502678687)},
 'cholesky': {'ridge__alpha': np.float64(0.4015672005492643)},
 'lsqr': {'ridge__alpha': np.float64(0.266100442379273)},
 'sparse_cg': {'ridge__alpha': np.float64(0.34630990437442755)},
 'sag': {'ridge__alpha': np.float64(0.6242067008992809)},
 'saga': {'ridge__alpha': np.float64(0.19710464482571677)},
 'lbfgs': {'ridge__alpha': np.float64(3.809880389408593)}}